name: Test and build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout and Setup Node
        uses: ./.github/actions/setup-node-install-npm
      - name: Check formatting with prettier
        run: npm run format:check

  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout and Setup Node
        uses: ./.github/actions/setup-node-install-npm
      - name: Npm audit
        run: |
          npm config set audit-level critical
          npm audit --registry="https://registry.npmjs.org"

  test-angular:
    runs-on: ubuntu-latest
    needs: [audit, prettier]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout and Setup Node
        uses: ./.github/actions/setup-node-install-npm
      - name: Run unit tests
        run: npm run test:ci

  test-cypress:
    runs-on: ubuntu-latest
    needs: [audit, prettier]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout and Setup Node
        uses: ./.github/actions/setup-node-install-npm
      - name: Run cypress component tests
        run: npm run test:ci:component

  test-cypress-e2e:
    runs-on: ubuntu-latest
    needs: [audit, prettier]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout and Setup Node
        uses: ./.github/actions/setup-node-install-npm
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm start

  build:
    runs-on: ubuntu-latest
    needs: [test-angular, test-cypress]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout and Setup Node
        uses: ./.github/actions/setup-node-install-npm
      - name: Build app
        run: npm run build --if-present
